// The 66 books of the 1917 Bible, in canonical order. `nr` matches getbible's
// book number; `slug` becomes the book id in our database; name/abbreviation are
// Swedish so the display stays consistent regardless of what the source calls the books.
export type BibleBook = { nr: number; slug: string; name: string; abbrev: string }

export const BIBLE_BOOKS: BibleBook[] = [
  { nr: 1, slug: '1mos', name: 'Första Moseboken', abbrev: '1 Mos' },
  { nr: 2, slug: '2mos', name: 'Andra Moseboken', abbrev: '2 Mos' },
  { nr: 3, slug: '3mos', name: 'Tredje Moseboken', abbrev: '3 Mos' },
  { nr: 4, slug: '4mos', name: 'Fjärde Moseboken', abbrev: '4 Mos' },
  { nr: 5, slug: '5mos', name: 'Femte Moseboken', abbrev: '5 Mos' },
  { nr: 6, slug: 'josua', name: 'Josua', abbrev: 'Jos' },
  { nr: 7, slug: 'domarboken', name: 'Domarboken', abbrev: 'Dom' },
  { nr: 8, slug: 'rut', name: 'Rut', abbrev: 'Rut' },
  { nr: 9, slug: '1sam', name: 'Första Samuelsboken', abbrev: '1 Sam' },
  { nr: 10, slug: '2sam', name: 'Andra Samuelsboken', abbrev: '2 Sam' },
  { nr: 11, slug: '1kon', name: 'Första Konungaboken', abbrev: '1 Kon' },
  { nr: 12, slug: '2kon', name: 'Andra Konungaboken', abbrev: '2 Kon' },
  { nr: 13, slug: '1kron', name: 'Första Krönikeboken', abbrev: '1 Krön' },
  { nr: 14, slug: '2kron', name: 'Andra Krönikeboken', abbrev: '2 Krön' },
  { nr: 15, slug: 'esra', name: 'Esra', abbrev: 'Esr' },
  { nr: 16, slug: 'nehemja', name: 'Nehemja', abbrev: 'Neh' },
  { nr: 17, slug: 'ester', name: 'Ester', abbrev: 'Est' },
  { nr: 18, slug: 'job', name: 'Job', abbrev: 'Job' },
  { nr: 19, slug: 'psaltaren', name: 'Psaltaren', abbrev: 'Ps' },
  { nr: 20, slug: 'ordsprak', name: 'Ordspråksboken', abbrev: 'Ordspr' },
  { nr: 21, slug: 'predikaren', name: 'Predikaren', abbrev: 'Pred' },
  { nr: 22, slug: 'hogavisan', name: 'Höga visan', abbrev: 'HV' },
  { nr: 23, slug: 'jesaja', name: 'Jesaja', abbrev: 'Jes' },
  { nr: 24, slug: 'jeremia', name: 'Jeremia', abbrev: 'Jer' },
  { nr: 25, slug: 'klagovisorna', name: 'Klagovisorna', abbrev: 'Klag' },
  { nr: 26, slug: 'hesekiel', name: 'Hesekiel', abbrev: 'Hes' },
  { nr: 27, slug: 'daniel', name: 'Daniel', abbrev: 'Dan' },
  { nr: 28, slug: 'hosea', name: 'Hosea', abbrev: 'Hos' },
  { nr: 29, slug: 'joel', name: 'Joel', abbrev: 'Joel' },
  { nr: 30, slug: 'amos', name: 'Amos', abbrev: 'Am' },
  { nr: 31, slug: 'obadja', name: 'Obadja', abbrev: 'Ob' },
  { nr: 32, slug: 'jona', name: 'Jona', abbrev: 'Jon' },
  { nr: 33, slug: 'mika', name: 'Mika', abbrev: 'Mik' },
  { nr: 34, slug: 'nahum', name: 'Nahum', abbrev: 'Nah' },
  { nr: 35, slug: 'habackuk', name: 'Habackuk', abbrev: 'Hab' },
  { nr: 36, slug: 'sefanja', name: 'Sefanja', abbrev: 'Sef' },
  { nr: 37, slug: 'haggai', name: 'Haggai', abbrev: 'Hagg' },
  { nr: 38, slug: 'sakarja', name: 'Sakarja', abbrev: 'Sak' },
  { nr: 39, slug: 'malaki', name: 'Malaki', abbrev: 'Mal' },
  { nr: 40, slug: 'matteus', name: 'Matteusevangeliet', abbrev: 'Matt' },
  { nr: 41, slug: 'markus', name: 'Markusevangeliet', abbrev: 'Mark' },
  { nr: 42, slug: 'lukas', name: 'Lukasevangeliet', abbrev: 'Luk' },
  { nr: 43, slug: 'johannes', name: 'Johannesevangeliet', abbrev: 'Joh' },
  { nr: 44, slug: 'apg', name: 'Apostlagärningarna', abbrev: 'Apg' },
  { nr: 45, slug: 'romarbrevet', name: 'Romarbrevet', abbrev: 'Rom' },
  { nr: 46, slug: '1kor', name: 'Första Korinthierbrevet', abbrev: '1 Kor' },
  { nr: 47, slug: '2kor', name: 'Andra Korinthierbrevet', abbrev: '2 Kor' },
  { nr: 48, slug: 'galaterbrevet', name: 'Galaterbrevet', abbrev: 'Gal' },
  { nr: 49, slug: 'efesierbrevet', name: 'Efesierbrevet', abbrev: 'Ef' },
  { nr: 50, slug: 'filipperbrevet', name: 'Filipperbrevet', abbrev: 'Fil' },
  { nr: 51, slug: 'kolosserbrevet', name: 'Kolosserbrevet', abbrev: 'Kol' },
  { nr: 52, slug: '1thess', name: 'Första Thessalonikerbrevet', abbrev: '1 Thess' },
  { nr: 53, slug: '2thess', name: 'Andra Thessalonikerbrevet', abbrev: '2 Thess' },
  { nr: 54, slug: '1tim', name: 'Första Timotheosbrevet', abbrev: '1 Tim' },
  { nr: 55, slug: '2tim', name: 'Andra Timotheosbrevet', abbrev: '2 Tim' },
  { nr: 56, slug: 'titusbrevet', name: 'Titusbrevet', abbrev: 'Tit' },
  { nr: 57, slug: 'filemon', name: 'Filemonbrevet', abbrev: 'Filem' },
  { nr: 58, slug: 'hebreerbrevet', name: 'Hebreerbrevet', abbrev: 'Hebr' },
  { nr: 59, slug: 'jakobsbrevet', name: 'Jakobsbrevet', abbrev: 'Jak' },
  { nr: 60, slug: '1petr', name: 'Första Petrusbrevet', abbrev: '1 Petr' },
  { nr: 61, slug: '2petr', name: 'Andra Petrusbrevet', abbrev: '2 Petr' },
  { nr: 62, slug: '1joh', name: 'Första Johannesbrevet', abbrev: '1 Joh' },
  { nr: 63, slug: '2joh', name: 'Andra Johannesbrevet', abbrev: '2 Joh' },
  { nr: 64, slug: '3joh', name: 'Tredje Johannesbrevet', abbrev: '3 Joh' },
  { nr: 65, slug: 'judas', name: 'Judasbrevet', abbrev: 'Jud' },
  { nr: 66, slug: 'uppenbarelseboken', name: 'Uppenbarelseboken', abbrev: 'Upp' },
]
